version: '3'

networks:
  laravel:

volumes:
  mysql:
    driver: local

services:
  nginx:
    image: nginx:stable-alpine
    container_name: podpoint-api
    ports:
      - "8000:80"
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
        - ./apidata:/var/lib/mysql
        - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: podpointapi
      MYSQL_USER: podpointapi
      MYSQL_PASSWORD: azertyuiop1234567890!
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  #App Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: phpapp
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
    - "8085:80"
    links:
    - mysql:db
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: phpmyadmin
      SERVICE_TAGS: dev
    working_dir: /var/www/html
  tester:
    build:
      context: .
      dockerfile: tester.Dockerfile

  frontend:
    build:
      context: .
    container_name: podpoint-front
    ports:
      - "8080:80"
    volumes:
      - ./front/public:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: podpoint-api-docs
    ports:
      - "8001:8080"
    volumes:
      - ./support/api-docs-swagger.json:/api-docs-swagger.json
    environment:
      SWAGGER_JSON: /api-docs-swagger.json
      # API_URL: ""
    networks:
      - laravel