
version: "3.1"
networks:
  fronetendnet:
    driver: bridge
services:

    webserver:
      image: nginx:alpine
      container_name: podpoint-front-webserver
      working_dir: /application
      volumes:
          - ./code:/code
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      links:
        - php

    php:
      build: phpdocker/php-fpm
      container_name: podpoint-front-php-fpm
      working_dir: /application
      volumes:
        - ./code:/code
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

